<?php

	$this->t('<h2>The Founding of Delta Kappa Epsilon</h2> 
	
 
<p style="TEXT-INDENT: 0.5in"><span style="color: black; font-size: 10pt;"><span style="background-color: #ffffff;">On Saturday, June 22, 1844, 15 Yale College undergraduates met in No. 12 Old South Hall and established a new society they called DELTA KAPPA EPSILON. </span></span><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="FONT-FAMILY: \'Arial\',\'sans-serif\'; COLOR: black; FONT-SIZE: 10pt"><span style="background-color: #ffffff;">The Fraternity\'s open motto, "Kerothen Philoi Aei" or </span><em><span style="background-color: #ffffff;">"Friends from the Heart, Forever"</span></em><span style="background-color: #ffffff;"> was adopted, as was the DKE pin and the secret grip.&nbsp; Below is an account of the founding as well as the earliest days of the Delta Kappa Epsilon fraternity.</span></span></span></span></p> 
<p style="FONT-FAMILY: " align="center"><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">THE FOUNDING OF THE FRATERNITY</span></span></span></span></p> 
<p style="TEXT-ALIGN: center; MARGIN: 0in 0in 6pt" align="center"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">AS RECALLED BY ONE OF THE FOUNDERS</span></span></p> 
<p style="TEXT-ALIGN: center; MARGIN: 0in 0in 6pt" align="center"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Edward Griffin Bartlett, Phi 1846</span></span><span style="font-family: arial, helvetica, sans-serif;">&nbsp;</span></p> 
<p style="TEXT-ALIGN: center; MARGIN: 0in 0in 6pt" align="center"><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">from</span></span></span></span></p> 
<p style="FONT-FAMILY: " align="center"><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">The Delta Kappa Epsilon Quarterly,</span></span></span></span></p> 
<p style="FONT-FAMILY: " align="center"><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">Vol.1, No.1.; January, 1883</span></span></span></span></p> 
<blockquote> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; It is a worn little book which lies before me; the cover marred and scratched, the paper yellow with age and the ink faded to a dull brown. The first page is half filled with my handwriting, and below are signed, beside my own, fourteen names--each marking sharply the individuality of the writer, and recalling the face of an old friend, each turning my thoughts to the end of the earth where he who bore it lives in active usefulness or rests in honored grave--all carrying me back to the day, a full generation ago, when we, fifteen boy classmates at Yale, formally avowed the bonds of mutual friendship which has long held us.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; The spring of 1844 seems a queer old time, as I recall it now. Yale was to us the great seat of learning of the world. Rivalry with Harvard had not been thought of, and in fact we knew too little and heard too rarely of the Cambridge school, to take even a languid interest in its welfare.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; Boating there was none. Baseball had not been invented. We played football with each other, and not according to Rugby. "The College Press" had then no existence. The great honors of the college were the commencement appointments, each of graded importance, all allotted among the twenty "oration men," who led their class in general standing.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; Scarcely secondary to these were the honors of the great literary societies, the "Brothers in Unity," and "Linonia." The membership in these societies extended throughout the four years course, and the rivalry between them was so intense that committees of each went as far as New York to interview probable freshmen, and impress them with the merits of the societies respectively.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; The most of the upper classmen lived in the college dormitories, where the seniors had the first choice of rooms, the juniors the second, and so on down to the freshmen. Our bitterest grievance was the iron rule which compelled attendance at five o\'clock-in-the-morning prayer, on which occasion cloak and boots at least were expected to be worn.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; Our most favored recreation was the "Beethoven" club with its orchestra and fifty trained voices. But the time was close to the line between the old and the new. Our class of \'46 received the last diplomas signed by President Day, and our class instituted the first gymnasium, bringing Sheridan from New York to instruct us for the first few months.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; There were then two so-called Junior societies at Yale, Psi Upsilon and Alpha Delta Phi. Their main object was to associate groups of students high in college standing, skillful in college politics, who should mutually co-operate to increase the share of honors which should fall to each, while another scarcely secondary aim was in secret meeting to enjoy private drill in oratory and composition--preparatory to the exercises of the open literary societies. Their aims were practical, their methods business-like. They claimed, too, to make their elections strictly in consideration of the character, as scholars and gentlemen, of the members of the class from which they were made, and that such elections, therefore, were a tribute to the high scholarship and character of the best men in such class.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; And, while others might have differed with them as to their application of their avowed rule, it came to be considered in each sophomore class that the leaders in scholarship and gentlemanly qualities had a right to, and might expect, an election. Such elections were made from the sophomore class in the spring term, and as, from the basis of the selection, the choice was practically anticipated, it was natural that those who considered themselves at the head of the class should associate together, and that, by the time such elections were announced, they were little more than formal invitations to those already considered to be entitled to them.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; For purposes of college exercises there were two divisions of our class of \'46, as there had been of preceding classes. But "division" feeling was peculiarly strong in our class. Hence it was, doubtless, that in each division there was a group of classmates whose opinion of each other was such that they confidently expected the most of the elections to Psi Upsilon and Alpha Delta Phi to be made from their number. Such at least was the case in the division of the class to which we belonged, and among those with whom I was intimately associated.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; There were quite a number, each of whom considered himself and was considered by his friends as entitled to the elections. But those of the other division had the most "friends at court," and when the elections were announced they were mainly from the rival division. So marked was the partiality with which the selection had been made, so prominent were the instances where merit had been slighted--as the event in College honors afterwards showed, that Psi Upsilon elections were rejected by several who had actually received them&mdash;and they were the most active in asking the cooperation of others, who had been slighted, to form a new Junior society.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; If to any one more than others is due the founding of Delta Kappa Epsilon, George Foote Chester is that man, though brother Sherwood was prominent in such respect. To be sure, I recall, as brother Chester\'s letter&mdash;now before me&mdash;states, that we found, on talking over matters with each other, that several among us had independently conceived the idea of a new Junior society.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; But Chester was at least one of the first who had planned such an association. And when we discussed the pros and cons, it was he who most strongly urged the new departure. It was peculiarly his zeal and arguments that did most to hasten our conclusion, and no one more than he was influential in deciding our plans in such regard.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; It was at a preliminary meeting held on June 22, 1844, that it was resolved to found a new society, and during the first week in July, 1844, the written articles now before me were drawn and signed, which bound us in preliminary organization.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; At this meeting our Greek motto was adopted, and the name Delta Kappa Epsilon definitely assumed. The matter of badges was then discussed, and a draft made by me, showing Delta Kappa Epsilon on a scroll, upon a diamond bearing a star in each corner, was handed to Inman the artist, who sketched it in its present shape, and suggested the addition of the word "Yale," which, being accepted, the pin was adopted as now used by the Phi chapter. Details of the permanent working plan of the organization were largely postponed until we had passed through, as we thought, quite successfully, the crisis of selecting a membership from the next class.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; We awaited anxiously, though confidently, the allotment of graduation honors in our class of \'46, since our avowed reason for founding a new fraternity had been our belief that the older Junior societies had not properly recognized in their elections, the scholarship of some of those who had joined in the new departure. And the result amply justified our claim. Honors fell, which among us, Case, Horton, Kinsley, Righter and Franklin each took an "Oration;" Conyngham and Jacobs received "first Colloquies" and Chester took "Second Dispute."</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; In other regards we were peculiarly fortunate. Horton was admittedly the foremost of his class in oratory, especially in extempore debate. One of our members was the leading athlete of the gymnasium, I was the leader of the "Beethoven," and the first who had ever held that office in his junior year, and every one was at least a fair scholar.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; Founded as Delta Kappa Epsilon was, we naturally made our elections on the basis upon which we had come together, and the early members&mdash;not invariably the best, and never poor, students&mdash;were always a companionable crowd. Such was Delta Kappa Epsilon from the start, adopting, without formulating the principle, that he lived his life best, who, helpful to his fellows, enjoyed it most himself.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; The new Fraternity had all the pleasure which came from self-confidence, and at once instituted itself as the rival of Psi Upsilon and the patronizing critic of Alpha Delta Phi&mdash;though it was doubtless some time before such status was recognized by these societies. Our numbers were so small that we were at first generally beaten when we contested elections. We were, however, fortunate in generally having just the men "wanted" when party spirit did not run high, were wide awake and decidedly workers. Our aim the first years was to make the Fraternity felt, and we were quick to see and improve every chance in this direction.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; In chapter we had at first but few customs except as to initiations, which were elaborate, contained no buffoonery, and were, as we thought, very impressive. Our literary exercises were always a great feature and very spirited.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; Most of what occurred in those days, much even connected with Delta Kappa Epsilon, has grown very dim in my memory; but our first meeting will never be forgotten. We had hired a front room in the second story of a building at the corner of Chapel and State Streets, the latter skirting the old canal, which, filled up, now forms the bed of the New York &amp; New Hampshire Railroad. We came at the appointed time and found the room&mdash;without a chair, table, lamp, or other article of furniture. Our landlord was sent for, but he calmly expressed his surprise that college students should not know the difference between chairs and a room. So we held a standing "session," nothing was tabled, and for dispatch of business the meeting was a model. I only hope it will afford now as much amusement to the Psi Upsilon&rsquo;s as it would then, had they known it.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; We had, at first, no idea of propagating chapters. Our body, however, became known and proved popular, and applications were received for charters for "branches." These were granted to bodies of friends associated like ourselves, when some member of our chapter could personally vouch for the character of the applicants. Thus it was brother Shapleigh who was the sponsor for Theta, which we almost immediately established at Bowdoin. He lived at Elliott, Me., and I at Portsmouth, N.H., about six miles distant. We seized the opportunity when vacation at Yale coincided with term time at Bowdoin, and Shapleigh, taking his father\'s horse and buggy, we drove to Brunswick.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; On the first day we drove from Portsmouth to Portland, stopping for dinner at a famous old half-way hostelry, and passing through Old Orchard, Kennebunk, and other little hamlets now grown into famous summer resorts. We drove the next day from Portland to Brunswick, where we were received with decided coolness by the faculty, who knew our errand. Professor Packard, a cousin of Shapleigh, carried this so far that he declined to invite me to a commencement party which he was about to give, the consequence of which was that Shapleigh would not attend, and we used the evening to good advantage in canvassing the proposed charter members.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; We were favorably impressed with the men, among whom was Shapleigh\'s friend Fogg. But as they were not all Juniors, we advised that the fraternity be made to take in the three upper classes instead of one only. In accordance with the original idea, the number was to be limited to fifteen. We had several meetings for consultation, and arranged everything as completely as possible, so that Sherwood, when he came on the next fall, had nothing to do but perform the initiation and impart the mysteries.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; So far as we discussed our aims they were mainly those of the societies already in existence&mdash;facilities for literary drill, co-operation in college politics, companionship in recreation. There was, however, one circumstance not counted upon by us at the time which fixed the determining characteristic of Delta Kappa Epsilon.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; The little band of its founders had gathered without definite design on the part of those concerned, simply because mutual attraction had drawn together young men of congenial temperament. It was this that had proved stronger than the inducements of the junior societies, which would otherwise have severed us; it was this that, controlling our plans, made Delta Kappa Epsilon from its institution somewhat different from the other "societies" of Yale, and, beyond others, a "fraternity."</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="color: black; font-size: 10pt;"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; We builded better than we knew, when we founded the brotherhood to which good fellowship has ever been a passport not less requisite than learning, where glees have been written as often as essays, and where the candidate most favored was he who combined in the most equal proportions the gentleman, the scholar, and the jolly good-fellow.</span></span></span></span></p> 
<p style="FONT-FAMILY: "><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: x-small;"><span style="FONT-FAMILY: \'Arial\',\'sans-serif\'; COLOR: black; FONT-SIZE: 10pt"><span style="font-family: arial, helvetica, sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp; We took a deep interest in the Fraternity\'s welfare, not because we had planned for it an elaborate future, but because it had been the nucleus within which were comprised, or about which were grouped, the dearest memories of Yale; and it is probably just that lack, in the selection of members, of all inflexible rules but one&mdash;that the candidate must be a gentleman in the best sense of the word, to which Delta Kappa Epsilon owed, by which, if at all, she </span><span style="font-size: x-small;"><span style="font-family: arial, helvetica, sans-serif;">deserved </span></span><span style="font-family: arial, helvetica, sans-serif;">her success.</span></span></span></span></p> 
</blockquote> 
<p style="padding-left: 30px;"><span style="line-height: 115%; font-family: \'Arial\',\'sans-serif\'; color: black; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><span style="font-size: small;"><span style="font-family: arial, helvetica, sans-serif;">- Edward Griffin Bartlett</span><span style="font-family: arial, helvetica, sans-serif;">, Phi, 1846</span></span></span></p> 

<h2>The Founding of Cornell\'s Delta Kappa Epsilon Chapter, Delta Chi</h2> 


<p style="text-align: left;"><span style="font-size: small;">&nbsp;&nbsp;&nbsp;&nbsp; At precisely 8 o\' clock P.M., February 11th, 1870, the first members of our Delta Chi chapter of Delta Kappa Epsilon "Swung out"--they celebrated the chartering of DKE at Cornell University--with an&nbsp;</span><span style="font-size: small;"><span style="font-size: small;">inaugural dinner held at the Clinton House, 116 North Cayuga Street.</span></span><span style="font-size: small;"><span style="font-size: small;">&nbsp;</span></span><span style="font-size: small;"><span style="font-size: small;">Below is&nbsp;</span></span><span style="font-size: small;"><span style="font-size: small;">our Alumni Historian\'s</span></span><span style="font-size: small;"><span style="font-size: small;">&nbsp;account of this affair as well as excerpts from his history of the founding and early years of the Cornell chapter of Delta Kappa Epsilon</span></span><span style="font-family: arial, helvetica, sans-serif; font-size: small;">.</span></p> 
<p style="text-align: center;"><span style="font-size: small;">The Deke House at Cornell</span></p> 
<p style="text-align: center;"><span style="font-size: small;">A Concise History of the Delta Chi Chapter of Delta Kappa Epsilon, 1870-1930</span></p> 
<p style="text-align: center;"><span style="font-size: small;">H. William Fogle, Jr. &Delta;&Chi; of &Delta;&Kappa;&Epsilon; &lsquo;70</span></p> 
<blockquote> 
<h2><span style="font-size: small;">Founding</span></h2> 
</blockquote> 
<blockquote> 
<p><span style="font-size: small;">The story of the Delta Chi chapter must be preceded by some mention of the Fraternity\'s general state at the end of the Civil War. Up until that great national schism, DKE had enjoyed years of prosperity and rapid expansion since its founding at Yale on 22 June 1844. By 1860, ten colonies were established in the south and nineteen in the north. The war was to disrupt college life throughout the fractured union as students were drained from academia to fill the ranks of the embattled armies and many institutions simply closed their doors for the duration. These chaotic conditions arrested the growth of the Fraternity during the war years, but recovery was prompt and during the early years of the Reconstruction we find charters being granted to Psi Phi (DePauw) in 1866, Gamma Phi (Wesleyan), Eta Alpha (Washington and Lee) and Psi Omega (Rensselaer) in 1867, and Beta Chi (Western Reserve) in 1868.</span></p> 
<p><span style="font-size: small;">Cornell University had barely been opened when the first discussion of expanding the Fraternity to Ithaca took place in October 1868 at the 22nd DKE Convention hosted by the Sigma (Amherst) chapter. Brother John James McCook, Lambda \'66, serving as the president of the convention, introduced a motion "that a committee be appointed by the Phi Chapter to ascertain the facilities for the establishment of a chapter of DKE in Cornell University and to report at the next annual convention or at such time as may seem fit." The motion carried, but we know nothing about the composition of that first committee or its activities. Alas, the records of Mother Phi have been lost.</span></p> 
<p><span style="font-size: small;">A conservative policy towards expansion then took hold within DKE and the next convention, the 23rd at Theta (Bowdoin) held during October 1869, rejected three applications for charters, a trend that was to continue with rare exceptions until the end of the century. Nevertheless, the Cornell question was again raised and Brothers Edwin Forrest Sweet, Phi \'71, Charles Hopkins Clark, Phi \'71, and William Hill Sloan, Beta Phi \'70, were appointed to investigate the situation in Ithaca. The Convention further authorized Phi to grant a charter pending a favorable report from this committee.</span></p> 
<p><span style="font-size: small;">Several of the old line fraternities had already established themselves at Cornell by this time. Zeta Psi, Chi Phi and the Kappa Alpha Society arrived in 1868, and Alpha Delta Phi, Chi Psi, Phi Kappa Psi and Delta Upsilon followed in 1869. Cornell President Andrew D. White, himself an enthusiastic member of Psi Upsilon (Yale, &rsquo;53), played a part in making the fledgling University hospitable to the Greek letter society movement. Opposition to fraternities, often heated, developed immediately, but the Independents, as they called themselves, could not stem the tide of the secret societies.</span></p> 
<p><span style="font-size: small;">Clark and Sloan arrived in Ithaca during the first week of 1870 and found just the material that they were looking for in the new student body. Aided by two older brothers, Professor Eli Whitney Blake, Jr., Phi \'57 of the Cornell faculty, and Thomas Morris Strong, Phi Chi \'68, at that time a medical student, they promptly recruited five men as the nucleus of the new chapter: James Julius Chambers \'70, Sidney Howard Soule \'71, John Milton McNair \'71, John DeWitt Warner \'72 and Sewellyn Ellsbree \'73. The earliest chapter records have it that Clark and Sloan "gave to these men aforesaid the oath and made them members of the Fraternity. Mr. Sweet came a short time afterwards and succeeded, with the aid of the gentlemen mentioned" in adding Patrick William Cullinan \'72, Frank DeElwin Nash \'72, Darius Adams Ogden, Jr. \'72, Charles Victor Parsell \'72 and Ambrose Clothier Pike \'72 as pledges.</span></p> 
<p><span style="font-size: small;">On 10 Jan 1870, Brother Sweet gave "to the ten men mentioned above the oath, [the] grip of the Fraternity, and declared them to be members of the Delta Chi Chapter of Delta Kappa Epsilon." This action by a representative of the Phi chapter formally chartered the Delta Chi Chapter. This new outpost of DKE immediately organized itself, elected officers (Chambers, McNair, Soule, Cullinan and Warner) and prepared for further recruits. The record is somewhat ambiguous, but the first president of the chapter was almost certainly Chambers, the only senior in the group.</span></p> 
<p><span style="font-size: small;">The first formal business meeting of the Delta Chi chapter took place on the following day at the Ithaca House on State Street where many of the charter members resided. The chapter\'s finances were put in order by declaring a substantial initiation fee of $26 per member and a committee was formed to pledge, among others, William McKenzie Hughes \'73, Henry Alonzo Monfort \'73 and Ebenezer Barton Kellogg \'73.</span></p> 
<p><span style="font-size: small;">But just what was the business of this little society? The answer was to be found in the openly declared Objects of Delta Kappa Epsilon: "...the cultivation of general literature and social culture, the advancement and encouragement of intellectual excellence, the promotion of honorable friendship and useful citizenship, the maintenance of gentlemanly dignity, self respect and morality in all circumstances, and the union of stout hearts and kindred interests to secure to merit its due reward."</span></p> 
<p><span style="font-size: small;">In 1870, words meant what they said, and the "cultivation of general literature" became the order of the day. The "Objects" said nothing about housing, feeding, drinking or carousing. The young Cornellians who gathered for these first chapter meetings were serious and ambitious students out to make a name for themselves at Cornell and in the world beyond. So the Fraternity was essentially a literary society with a side agenda of convivial social intercourse. There would be time for baseball and oyster dinners, but the important issue at hand was to master the University\'s publications. Thus we find that the chapter\'s second meeting on 25 January was devoted to coming to terms with Alpha Delta Phi concerning a role for DKE on the board of The Cornellian and then taking steps to control the Irving Society, a Cornell literary association.</span></p> 
<p><span style="font-size: small;">Of the charter members, two stand out in this vein. Julius Chambers \'70 would soon achieve the distinction of becoming the class Senior Essayist and go on to a distinguished career in journalism of which we will hear more. And John DeWitt Warner, a most serious student of classics, would later make his mark in law, politics and the arts. More than any of the other early Dekes, he would guide the chapter on its course to distinction at Cornell.</span></p> 
<p><span style="font-size: small;">The founding of Delta Chi was celebrated on 11 February 1870, the date that the chapter officially "swung out," with an elegant inaugural dinner held at the Clinton House, 116 North Cayuga Street.The affair was timed to follow the annual contest between Cornell\'s two open literary clubs, an event the Dekes were keenly interested in since Chambers was the Senior Essayist for the Irving Society. In later years, the House would celebrate this date with great feasts also held in the Clinton House. Finally, it might be noted that 11 February 1870 is sometimes taken as the issue date for the chapter\'s charter. This is certainly not the case, but one would not substantively incorrect in saying that the charter took force "at precisely eight o\'clock" on this festive February evening.</span></p> 
<h2><span style="font-size: small;">The First Hall of DKE</span></h2> 
<p><span style="font-size: small;">The fraternity conducted its early meetings in the rooms of members, many of whom resided in the Ithaca House, a local hotel on State Street. Thus the early records indicate meetings held in the rooms of Chambers, Kellogg, Sabin, Warner, et al. This arrangement soon found to be cumbersome and a committee was formed to find a proper meeting hall in June of 1870. The Dekes considered sharing rooms with the Masons in a new building that was being erected by one Colonel Charles Farrar Blood (1826-98), but the price was dear: one thousand dollars. The chapter came closer in the following fall academic term when negotiations with a Mr. Babcock offered the use of a room in the new Sprague block for four hundred dollars per annum. The chapter counter offered with $330 and eventually settled on the sum of $350. The brothers obtained the use of this room from 3 June 1871 until 30 April 1873.</span></p> 
<p><span style="font-size: small;">From the beginning the chapter kept detailed accounts of every meeting in large leather bound minute books. Our detailed knowledge of Delta Chi\'s history comes largely from these records. In a period covering nearly one hundred and twenty years, only a few short intervals are omitted from this substantial manuscript. The historian blesses the good fortune of the chapter to secure the Sprague block meeting hall when it did for the Ithaca House burned to the ground on 28 August 1871 and we might otherwise have lost the first precious volume of minutes.</span></p> 
<h2><span style="font-size: small;">Cornell\'s Greek Community</span></h2> 
<p><span style="font-size: small;">Delta Chi quickly realized that the rivalry between competing fraternities could become unmanageable. In October of 1870, a motion "to form a league in conjunction with Alpha Delta Phi, Delta Upsilon, Phi Kappa Psi, and Theta Delta Chi" carried. Negotiations stumbled when Delta Chi resolved to break off the combination if Alpha Delta Phi "put up Mr. Cullinan.&rdquo; The Alpha Delts did not blink and the alliance did not coalesce. Some years later Delta Chi would explore the possibility of combining with Alpha Delta Phi, Psi Upsilon, and Kappa Alpha to issue a secret society publication. This would eventually lead to the formation of a strong and enduring cartel named the Star League, and Delta Kappa Epsilon would take its place along with Alpha Delta Phi, Psi Upsilon, Kappa Alpha, and Zeta Psi as one of the commanding powers at Cornell.</span></p> 
<p><span style="font-size: small;">Delta Chi\'s influence on the hill was noteworthy in the early years. The members deliberately strove for student honors and class offices. In this they achieved much success. The Cornellian, at that time exclusively a fraternity publication, became a Delta Chi fiefdom. This was not accomplished without ruffling the feathers of the sister fraternities. The editorial board of The Cornell Era also bore the stamp of DKE. Dekes held office, often the presidency, in the Irving, the Adelphi, the Orpheus, the Natural History Society, and the Historical Society. Several brothers obtained leading positions in the Cadet Brigade.</span></p> 
<p><span style="font-size: small;">The chapter members were more than prominent in athletics. The University\'s first boat was manned with a crew of four Dekes who later founded the Cornell Navy, the predecessor of today\'s crew team, and built the first boat house. The Baseball Club was captained and largely composed of brothers in DKE. This could also be said of the Cricket Club. However the crowning achievement was the establishment of a Cornell Athletic Association led by three Dekes (Warner \'72, Charles Addison Wheeler \'74 and Earnest Grey Sawyer \'74) and the erection of a new gymnasium that was funded entirely by a campaign run by Brother Wilbray James Thompson \'74.</span></p> 
<h2><span style="font-size: small;">Fraternity Affairs</span></h2> 
<p><span style="font-size: small;">The chapter was determined to become active in the Fraternity\'s affairs beyond the bounds of Ithaca. The Delta Chi delegation to the 24th DKE Convention hosted by Upsilon (Brown University) was instructed "to try to have the next Convention at Cornell" and to their credit, they succeeded. On 25 October 1871, the Delta Chi Chapter welcomed brothers from all over the country who descended upon Cascadilla Hall for the 25th DKE Convention. The arrangements for this occasion were elaborate and carried off with considerable style. Furthermore, the Cornell Dekes led the effort to establish a new colony of Delta Kappa Epsilon at Syracuse University: the Phi Gamma Chapter.</span></p> 
<h2><span style="font-size: small;">Literary Exercises</span></h2> 
<p><span style="font-size: small;">The Literary Exercise as a permanent aspect of the chapter\'s meetings was born in February of 1871 and would continue in good health up until World War II. These exhibitions could take many forms: the reading of an essay or poem, a recitation, a discussion of a current news topic, or very often, a debate. These exercises were taken seriously and often became the principal justification for the meeting. Debate topics were assigned in advance and covered a broad range of social and academic matters. Thus we have the brothers vigorously engaged over issues such as, "The Question of Polygamy in reference to the U. S. Government," and "That the United States should declare war against Spain on account of the Cuban affair.&rdquo;</span></p> 
<h2><span style="font-size: small;">Chapter Organization and Life</span></h2> 
<p><span style="font-size: small;">The organization of the chapter was simple and not unlike that of other fraternities. From the beginning, the elected officers were conventionally titled as president, vice-president, corresponding secretary, recording secretary, treasurer, orator, poet, essayist and guide. The position of registrar was added in 1871. Ad hoc committees were appointed to handle specific tasks such as renting a meeting hall or purchasing furniture. In 1872, the titles for the principal officers changed: the president became Pater Primus, the vice-president became Pater Secundus, the corresponding secretary became Scriptor, the recording secretary became Scriba and the treasurer became known as Custos. The functionary positions of Chorister, Chaplain and Literary Exercise Critic were also added shortly thereafter. The House officers would continue to use these titles until 1885 when the new centralized DKE organization effectively standardized ritual throughout the Fraternity.</span></p> 
<h2><span style="font-size: small;">The Hayes Legacy</span></h2> 
<p><span style="font-size: small;">The chapter had in its earliest days set upon a policy that it was destined to reverse before the end of its first decade, and in doing so, obtained a great distinction for itself and the Fraternity at large. The policy in question concerned "honorary members," and Delta Chi took the position in 1873 that Delta Kappa Epsilon should not tolerate the custom of bestowing honorary memberships on dignitaries or friends even though it was a common practice in other fraternity and academic societies. Thus, Delta Chi instructed Brother Frederick Baker \'74, her delegate to the forthcoming 26th DKE Convention, "to vote against all applications for new chapters [and] proposals for Honorary Members" and to encourage an amendment to the Fraternity Constitution requiring a unanimous vote to pass such resolutions. It is somewhat ironic that the chapter took such a strong position in light of the fact that Cornell Professor Bayard Taylor, an honorary Deke from the Omicron chapter, was a devoted friend and advisor to the brotherhood.</span></p> 
<p><span style="font-size: small;">The reputation and accomplishments of the Delta Chi chapter was such that it could selectively choose its members from the top tier of the University\'s freshmen class. Thus it is not surprising that, after a determined rush in the fall of 1873, the chapter recruited a certain Birchard Austin Hayes \'74 who later rose to be twice elected as the House\'s Pater Primus. Birchard was soon followed into DKE by his younger brother, Webb Cook Hayes \'76. In time the two youngest Hayes brothers, Rutherford Platt \'80 and Scott Russel \'92, and a cousin, Walter Justin Sherman \'77 would become Cornell Dekes. Rutherford Birchard Hayes, Kenyon \'42, the father of the brothers who bore his name, would also bequeath a grandson, Walter Sherman Hayes \'18, to the Delta Chi chapter of Delta Kappa Epsilon. The Hayes family is perhaps the most distinguished of the House\'s many legacy groups.</span></p> 
<p><span style="font-size: small;">Understandably, the end of Delta Chi\'s opposition to honorary members came with the disputed election of Rutherford Hayes as the nation\'s 19th president in 1876. The following year saw Delta Chi petitioning the 31st DKE Convention to bestow the honor of membership in Delta Kappa Epsilon to the nation\'s new chief executive. Brother George Pierre Erhard, Gamma Beta \'79, speaking as the Chairman of the Committee on Honorary Members, reported "favorably on this name" on 11 October 1877. Several days later, Brother William Lesley Sheafer, Rho \'78, the convention\'s secretary, wrote to Rutherford Platt Hayes asking him to give an enclosed letter tendering the honorary membership to his father during the coming Christmas holiday. A second letter from Shaefer, nervously asking if the offer was accepted, survives. His anxiety was unnecessary; the elder Hayes had been a staunch advocate of his son\'s membership in DKE at Cornell, personally paying the House fees for Birchard and Webb. Thus, Rutherford Birchard Hayes became the first president with the distinction of membership in an American College fraternity.</span></p> 
<h2><span style="font-size: small;">The First DKE Lodge</span></h2> 
<p><span style="font-size: small;">The matter of finding a proper lodge for the Cornell Dekes was a pressing issue. Delta Chi could not hope to vie with her sister fraternities without a suitable residential establishment. The problem was resolved in the late spring of 1877 when the brotherhood made arrangements to exclusively occupy a suitable building located at 111 Ozmun Place. This prominent two story structure, owned by John O. Marsh and Edwin M. Hall, would become the first Deke House. &nbsp;Although the rooms were leased individually by the brothers, and not all were needed, the chapter voted to rent the empty spaces as well to keep outsiders away and further resolved "that the house be considered a fraternity house." The Dekes wasted no time in celebrating with an elegant party on 29 May 1877 for alumni and Cornell DKE faculty members in their new abode.</span></p> 
<p><span style="font-size: small;"><span style="font-size: small;">The new House, though not an architectural achievement, was comfortable and conveniently located on a corner lot near the campus. It would suffice until a permanent lodge could be built. The establishment provided individual rooms and a common area, but not a dining hall. There was also no provision for a lodge room. Thus, the DKE Hall in the Morrison block down town would continue to be used for meetings of the brotherhood until it was given up in the summer of 1879.</span></span></p> 
<p><span style="font-size: small;"><span style="font-size: small;">The Ozmun Street Deke House was arguably the first fraternity lodge at Cornell, a distinction usually accorded to the Alpha Delta Phi house built nearby a year later, in 1878, on the southeast corner of East Buffalo and Spring Streets, halfway up the hill. Admittedly, the Alpha Delts did own their fine brick building which was fully appointed for the needs of gentlemanly Greek life. In 1883, Delta Chi would claim that theirs was the second best fraternity house on the hill, the Alpha Delta Phi house being the acknowledged best, the Psi Upsilon ranking third, and the Zeta Psi fourth. All of the other fraternities were housed in "business blocks" at the time.</span></span></p> 
<p><span style="font-size: small;"><span style="font-size: small;">By the end of the eighteen-seventies Delta Chi had initiated or affiliated some ninety-six men. Of those, four died before the coming of 1880 and one had been expelled. By any measure, the chapter had established itself at Cornell as a major fraternity.</span></span></p> 
</blockquote> 
<p>&nbsp;</p> 
<p style="padding-left: 30px;"><span style="font-size: small;"><span style="font-family: arial, helvetica, sans-serif;">- H. William Fogle, Jr. &Delta;&Chi; of &Delta;&Kappa;&Epsilon; &lsquo;70</span></span></p> 
<p style="padding-left: 30px; "><span style="font-family: arial, helvetica, sans-serif;"><span id="_marker">&nbsp;</span></span></p> 
<p>&nbsp;</p>');
?>